/**
 * Titan Spectrum v1.0 — official palette
 */
export const colors = {
  bgPrimary: "#070B14",
  bgSecondary: "#0F172A",
  bgTertiary: "#172033",
  surface1: "#111827",
  surface2: "#1B2538",
  surface3: "#24324A",
  blue: "#3B82F6",
  purple: "#8B5CF6",
  cyan: "#06B6D4",
  green: "#22C55E",
  orange: "#F59E0B",
  red: "#EF4444",
  pink: "#EC4899",
  textPrimary: "#F8FAFC",
  textSecondary: "#CBD5E1",
  textMuted: "#94A3B8",
  success: "#22C55E",
  warning: "#F59E0B",
  danger: "#EF4444",
  info: "#3B82F6",
  /** @deprecated use blue */
  titanBlue: "#3B82F6",
  titanPurple: "#8B5CF6",
  titanCyan: "#06B6D4",
  titanGreen: "#22C55E",
  titanOrange: "#F59E0B",
  titanPink: "#EC4899",
  arenaBlue: "#3B82F6",
  electricCyan: "#06B6D4",
  auroraPurple: "#8B5CF6",
  emeraldSuccess: "#22C55E",
  premiumGold: "#F59E0B",
  darkSpace: "#070B14",
  surfaceCard: "#111827",
  surfaceElevated: "#1B2538",
} as const;

export const cssColorVars = {
  "--bg-primary": colors.bgPrimary,
  "--surface-1": colors.surface1,
  "--blue": colors.blue,
  "--purple": colors.purple,
  "--cyan": colors.cyan,
  "--green": colors.green,
  "--orange": colors.orange,
  "--pink": colors.pink,
  "--red": colors.red,
  "--text-primary": colors.textPrimary,
  "--text-secondary": colors.textSecondary,
  "--arena-blue": colors.blue,
  "--electric-cyan": colors.cyan,
  "--aurora-purple": colors.purple,
  "--dark-space": colors.bgPrimary,
  "--surface-card": colors.surface1,
} as const;
